### ISSUE TITLE
Change UI to look more like mockup

### ISSUE THREAD

**Issue by sifex** [sifex/Scarlet#27]
[http://alexsinnott.me/home/images/scarlet_slide_browser_large_2x.png](http://alexsinnott.me/home/images/scarlet_slide_browser_large_2x.png)

**Comment by MontyBravo** [comment]
If possible to have that mock-up in a  similar way to the original Scarlet ?
i.e. separate lil window rather then using the full size chrome/firefox window ?

**Comment by sifex** [comment]
Released as part of Project Electron.
